/**
 * Turn slug like `users` or `user-profile` into camelCase for identifiers.
 */
export function slugToCamelCase(slug: string): string {
  const normalized = slug
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-');
  const parts = normalized.split('-').filter(Boolean);
  if (parts.length === 0) return 'resource';
  return (
    parts[0] +
    parts
      .slice(1)
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join('')
  );
}

export interface GenerateRouteOptions {
  /** URL segment for the comment, e.g. `users` */
  mountPath: string;
}

export function generateRouteSource(slug: string, options: GenerateRouteOptions): string {
  const camel = slugToCamelCase(slug);
  const routerName = `${camel}Router`;
  const schemaName = `${camel}PostBodySchema`;
  const mount = options.mountPath.startsWith('/') ? options.mountPath : `/${options.mountPath}`;

  return `/**
 * Generated by express-zod-routes — mount with:
 *   app.use('${mount}', ${routerName});
 */
import { Router } from 'express';
import { z } from 'zod';
import { validate } from 'express-zod-routes';

const router = Router();

const ${schemaName} = z.object({
  // TODO: define body fields
  name: z.string().min(1),
});

router.post('/', validate({ body: ${schemaName} }), (req, res) => {
  const body = req.validated!.body;
  res.status(201).json({ ok: true, data: body });
});

export const ${routerName} = router;
export default router;
`;
}

export function routeFileName(slug: string): string {
  const safe =
    slug
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/^-+|-+$/g, '') || 'route';
  return `${safe}.routes.ts`;
}
